name: Python Tests

on:
  push:
    branches: [ main, master, test ]  # Запускаем при push в основные ветки и в test
  pull_request:
    branches: [ main, master ]        # Запускаем при PR в основные ветки
  workflow_dispatch:                  # Позволяет запускать workflow вручную

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'  # Используем Python 3.9 как в amvera.yaml
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-mock pytest-cov
        # Устанавливаем точные версии зависимостей из requirements.txt
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        # Запускаем все тесты в директории tests/ с подробным выводом
        pytest -xvs tests/
        # Опционально: запускаем тесты с покрытием кода
        # pytest --cov=services tests/test_image_service.py 